version: 0.0
os: linux 
files:
  - source: /tegmen
    destination: /root/tegmen
hooks:
  # ApplicationStop:
  #   - location: 
  #     timeout:
  #     runas:
  # BeforeInstall:
  #   - location: 
  #     timeout:
  #     runas: 
  AfterInstall:
    - location: tegmen/scripts/after_install.sh
      runas: root
  # ValidateService:
  #   - location:     
  #     timeout: 
  #     runas: