[package]
name = "test_webserver"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
rspc = "0.2.0"
rspc-axum = { version = "0.1.1", features = ["ws"] }
tokio = { version = "1.37.0", features = ["full"] }
