[package]
name = "temperature_lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
aws_lambda_events = "0.15.1"
http = "1.1.0"
lambda_runtime = "0.11.2"
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["full"] }
